languageCode = "it"
languageName = "Italian"
weight = 1
title = "micheledinelli"

[params]
displayName = "IT"
isoCode = "it"
rtl = false
dateFormat = "2 January 2006"
    
[params.author]
  name = "Michele Dinelli"
  image = "avatar.png"
  headline = "MSc student, teaching tutor and research fellow [@unibo](https://www.unibo.it)."
  links = [ { email = "mailto:dinellimichele00@gmail.com" }, { github = "https://github.com/micheledinelli" }, { gitlab = "https://gitlab.com/micheledinelli" }, { linkedin = "https://linkedin.com/in/michele-dinelli" }, { x-twitter = "https://twitter.com/michele_dinelli" }, { graduation-cap = "https://www.unibo.it/sitoweb/m.dinelli"} ]
  bio = ""
