languageCode = "en"
languageName = "English"
weight = 1
title = "micheledinelli"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"

[author]
name = "Michele Dinelli"
image = "avatar.png"
headline = "MSc student and teaching tutor"
links = [ { email = "mailto:m.dinelli@unibo.it" }, { github = "https://github.com/micheledinelli" }, { gitlab = "https://gitlab.com/micheledinelli" }, { linkedin = "https://linkedin.in/michele-dinelli" }, { twitter = "htpps://twitter.com/michele_dinelli" } ]
bio = "Michele Dinelli"
