[[main]]
  name = "teaching"
  pageRef = "teaching"
  weight = 1
  
[[main]]
  name = "projects"
  pageRef = "projects"
  weight = 2

[[main]]
name = "about"
pageRef = "about"
identifier = "FNA5ZZOwoj"
weight = 3

[[footer]]
  name = "tags"
  pageRef = "tags"
  weight = 1

[[footer]]
  name = "teaching"
  pageRef = "teaching"
  weight = 2

[[footer]]
  name = "projects"
  pageRef = "projects"
  weight = 3

[[footer]]
  name = "about"
  pageRef = "about"
  weight = 4