colorScheme = "mich"
defaultAppearance = "dark"
autoSwitchAppearance = false
enableSearch = true
enableCodeCopy = true
mainSections = ["teaching", "projects"]
showViews = false
showLikes = false
robots = "all"
disableTextInHeader = false
highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = true

[header]
layout = "fixed"

[footer]
showMenu = true
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "profile"
showRecent = true
showRecentItems = 10
cardView = true

[article]
showDate = false
showAuthor = false
showBreadcrumbs = true
showDraftLabel = false
showEdit = true
editUrl = "https://github.com/micheledinelli/micheledinelli.github.io/blob/main/content/"
editAppendPath = true
showWordCount = true
showZenMode = true
# sharingLinks = ["twitter", "linkedin", "reddit", "email"]

[list]
layoutBackgroundBlur = false
layoutBackgroundHeaderSpace = false
showBreadcrumbs = true
showSummary = true
orderByWeight = true
groupByYear = false

[sitemap]
excludedKinds = [ "taxonomy", "term" ]

[taxonomy]

[term]

[firebase]

[fathomAnalytics]

[buymeacoffee]

[verification]
