baseURL = 'https://micheledinelli.github.io'
languageCode = 'en-us'
title = 'Michele Dinelli'
theme = 'brackets'

enableGitInfo = true

[params]
  name = 'Michele Dinelli'
  avatar = 'images/12.webp'

  [params.footer]
    # hide = true
    # hideCopyright = true
    # hidePoweredBy = true
    # hideSocial = true
    # hideBuild = true

  [params.social]
    github = 'https://github.com/micheledinelli'
    x = 'https://x.com/michele_dinelli'
    linkedin = 'https://www.linkedin.com/in/michele-dinelli/'

[menus]
  [[menus.main]]
    name = ' / '
    pageRef = '/'
    weight = 10
  
  [[menus.main]]
    name = 'Teaching'
    pageRef = '/teaching'
    weight = 20
  
  [[menus.main]]
    name = 'Projects'
    pageRef = '/projects'
    weight = 30
  
  [[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 40
